global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']  # เปลี่ยนจาก localhost เป็น prometheus

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: '/metrics'
    params:
      format: ['prometheus']

  - job_name: 'workers'
    static_configs:
      - targets: ['pushgateway:9091']
